### ISSUE TITLE
Damage rumble not disengaging after crash or mission exit

### ISSUE THREAD

**Issue by tpisko0427** [SimShaker-for-Aviators/SimShaker-for-Aviators-Releases#33]
As per the title.
Once you encounter any damage rumble doesn't disengage.
Need to close and restart SSA.
Would be great to fix this please.

**System (please complete the following information):**
 - Windows version: Win11
 - Simulator version: [DCS 2.9. Any]
 - SSA version: [SSA Beta 2.9.4 or previous]

Thank you
Tom

**Comment by f4l0** [comment]
On which model does this happen?

**Comment by tpisko0427** [comment]
I fly most modules and almost certain it happened on all I experienced damage with. Definitely F16, 18, AH64, A10. thanks

**Comment by GeorgeBrooker** [comment]
also having this issue on all planes. Fixed by turning my HF8 on and off using the big red button

**Comment by f4l0** [comment]
Which handler software do you use?
SimShaker Pad Handler?

**Comment by GeorgeBrooker** [comment]
I am using SSFA 3.0.0.0 although I was also getting this on the latest stable release, and seat handler 0.0.0.0 

<img width="1385" height="895" alt="Image" src="https://github.com/user-attachments/assets/0af3083f-0b1e-4278-9893-b5b1e495d5b2" />

It hapens less if ejection effects (and related like canopy effect and damage) are turned off as these are usualy what are firing at the time of death

**Comment by tpisko0427** [comment]
I am experiencing the same and have also reported it in the past. It is
still present for me on all modules. Any damages stays and carries forward.
I need to kill the seat and restart SSA to shed it off.
I'm on latest stable, latest DCS. Have HF8 seat.

**Comment by f4l0** [comment]
Can you easily reproduce this issue? If so, could you please record a session with the SSA tester?

**Comment by GeorgeBrooker** [comment]
> Can you easily reproduce this issue? If so, could you please record a session with the SSA tester?

Here is a log from SSA tester where I die at around 21:12:10 and the vibration continues even after reslotting. I turned off the engine in my new plane to confirm that wasn't the cause, and it continued to vibrate quite a bit regardless

[SSAlog.json](https://github.com/user-attachments/files/30539524/SSAlog.json)

<img width="822" height="309" alt="Image" src="https://github.com/user-attachments/assets/cc2f7bd6-a7ef-474f-a2bf-5300ade1f6c8" />

**Comment by GeorgeBrooker** [comment]
also bonus log from where the seat is going absolutely mad while sitting on the ground, and then also in the menu, this is all from the same continued vibration event in the previous log. The seat conitnued vibrating even after DCS was closed.
[vibrating at nothing.json](https://github.com/user-attachments/files/30539900/vibrating.at.nothing.json)

https://www.youtube.com/shorts/gC8X21R2H0U

**Comment by f4l0** [comment]
Can you also send me a SSA log when you crash the plane and it still continues to run? I wander if the DCS crash detection is working or not. You may see something like this:

<img width="665" height="37" alt="Image" src="https://github.com/user-attachments/assets/09e59806-4f6e-447a-8431-77993cf39317" />

**Comment by f4l0** [comment]
I might found a solution for the Seathandler... Might not work with the SimShaker Pad Handler but maybe andre can have a look here later...

**Comment by f4l0** [comment]
Should be fixed in the next alpha

**Comment by f4l0** [comment]
New alpha is available, please test if this fixes the issue on your side

**Comment by GeorgeBrooker** [comment]
> New alpha is available, please test if this fixes the issue on your side

Will do asap

**Comment by GeorgeBrooker** [comment]
I've done a quick smoke test and slammed a fulcrum into the ground about 20 times, seems good so far. I will need to test this live in multiplayer before I can say if its gone completely though. Thanks a lot for how quick you've got onto this! 

attached a log of it looking good if you want to review for your own interest

[lookgood.json](https://github.com/user-attachments/files/30617051/lookgood.json)

**Comment by GeorgeBrooker** [comment]
@f4l0 have a log for you where the rumble keeps going after I was killed by a missile. Dosn't seem to happen much on suicides but still relatively common when killed by an enemy (in multiplayer at least). I am using forcefeel as the output device (shows version 0.0.0.0, I have whatever came with the alpha build)

[vibrate.json](https://github.com/user-attachments/files/30868192/vibrate.json)

**Comment by GeorgeBrooker** [comment]
Log where it happens two more times. The vibration often stops at the time of death, but when I reslot in I have very strong vibration compared to the normal parking with engine on vibration, so it seems to be adding the effects back on reslot. this happsn at least twice in this log I think (too large for github to upload natively I think) https://drive.google.com/file/d/1nG03t3gOFPWkafWYwTBOUWrE-V_x_n2R/view?usp=sharing

restarting the seat handler via SSA fixes this every time
